### ISSUE TITLE
Can't launch the app

### ISSUE THREAD

**Issue by joceqo** [httpete-ire/timedo#3]
I previously used your pomodoro as it is the most awesome i had found on internet. But i lost the file, and now when i  try to launch it i end up with a lot of error. I have dl and npm install then npm start and open a tab on my 8080 local port but i get a GET /  404 error.. :/

**Comment by httpete-ire** [comment]
@nearee I will take a look at this over the weekend. 

You can use the app [here](https://timedo-rhqopfwgwd.now.sh/) for now, I'm glad you like it

**Comment by nearee** [comment]
Yes i saw, however it goes wild after the first cycle.. at least for me ( i.e. the break last 10 seconds and the work periods like 25 seconds). Sorry to point out all this, take your time; and thanks for sharing at least your amazing pomodoro

**Comment by nearee** [comment]
@httpete-ire  yes, it works super fine :) thank you for sharing ! Have a great day

**Comment by nearee** [comment]
there still the time problem after one cycle but i can totally get along with that

**Comment by httpete-ire** [comment]
@nearee I fixed that issue with the time after a cycle. Thanks for creating an issue


Published the latest version [here](https://zeit.co/htt_pete/timedo/meettdhrnm?redirect=1)

Can you confirm ifs fixed and I'll close the issue
